enforce_secure_profile: false
listeners:
  - query_port: 25577
    motd: '&1Another Bungee server'
    tab_list: GLOBAL_PING
    query_enabled: false
    proxy_protocol: false
    forced_hosts:
      pvp.md-5.net: pvp
    ping_passthrough: false
    priorities:
      - fallback
    bind_local_address: true
    host: 0.0.0.0:25565
    max_players: 100
    tab_size: 60
    force_default_server: false
remote_ping_cache: -1
network_compression_threshold: 256
permissions:
  default:
  admin:
    - bungeecord.command.server
    - bungeecord.command.list
    - bungeecord.command.alert
    - bungeecord.command.end
    - bungeecord.command.ip
    - bungeecord.command.reload
    - bungeecord.command.kick
    - de.uprank.cloudproxy.command.cloud
    - de.uprank.cloudproxy.notify
log_pings: true
connection_throttle_limit: 3
server_connect_timeout: 5000
timeout: 30000
stats: cad1c008-bd38-4440-9419-d2d6d8c78473
player_limit: 100
ip_forward: true
groups:
  Uprank:
    - admin
remote_ping_timeout: 5000
connection_throttle: -1
log_commands: false
prevent_proxy_connections: false
online_mode: true
forge_support: true
disabled_commands:
  - disabledcommandhere
servers:
  fallback:
    motd: '&1Just another Waterfall - Forced Host'
    address: localhost:12345
    restricted: false